name: Generate-BOM

on:
  push:
    paths:
      - 'pnp/cad/assembly.FCStd'
      - '.github/workflows/generate-bom.yaml'
    ignore-tags:
      - '*'
  pull_request:
    paths:
      - 'pnp/cad/assembly.FCStd'
    ignore-tags:
      - '*'
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  generate-bom:
    name: Generate BOM
    runs-on: ubuntu-latest

    steps:

    - name: Install FreeCAD Python library
      run:  |
        sudo apt install python3

    - name: Download repository
      uses: actions/checkout@v3

    - name: Fetch FreeCAD
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: "FreeCAD/FreeCAD"
        version: "tags/0.19.2"
        file: "FreeCAD_0.19-24291-Linux-Conda_glibc2.12-x86_64.AppImage"
        target: "FreeCAD.AppImage"
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Generate BOM file
      run:  |
            sudo chown runner:docker FreeCAD.AppImage
            chmod +x FreeCAD.AppImage
            ./FreeCAD.AppImage --appimage-extract > /dev/null
            cd pnp/cad
            python3 export-cad-bom.py

    - name: upload BOM results
      uses: actions/upload-artifact@v2
      with:
        name: bom
        path: pnp/cad/index_bom.md

    - name: Upload Artifacts to Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'release'
      with:
        files: |
          pnp/cad/index_bom.md

